/*
| ---------------------------------------------------------------------- 
| Add More Action Button / Menu
| ----------------------------------------------------------------------     
|
|
|
|
|
*/

const en = {
  'brandName': 'Name App',
  'noInternetConnection': 'No Internet connection',
  'lKhmer': 'Khmer',
  'lEnglish': 'English',
  'welcome': 'Welcome!',
  'enterYourMobileNumberToContinue': 'Enter your mobile number to continue',
  'languages': 'Languages',
  'loadLanguage': 'English',
  'selectLanguage': 'Select Language',
  'Seconds': ' s',
  'pleaseEnterYourPhoneNumber': 'Please Enter Your Phone Number',
  'phoneNumberIncorrect': 'Phone number incorrect',
  'continue': 'Continue',
  'download': 'Download',
  'seconds': 's',
  'confirmSMSCode': 'Confirm SMS code',
  'weHaveSentYouAndSMSWithThe': 'We have sent you and SMS with the',
  'codeTo': 'code to ',
  'IDidNotGetTheCode': 'I did not get the code',
  'IHaveAgreeTo': 'I’ve agree to',
  'the': 'the ',
  'termsAndConditions': 'terms and conditions',
  'loading': 'Loading...',
  'error': 'Error',
  'ok': 'OK',
  'yes': 'Yes',
  'no': 'No',
  'selectOption': 'Select Option',
  'DoYouWantToRemove': 'Do you want to remove?',
  'cancel': 'Cancel',
  'confirmation': 'Confirmation',
  'promotions': 'Promotions',
  'detail': 'Detail',
  'selectPackages': 'Select Packages',
  'seeAll': 'See all',
  'menu': 'Menu',
  'education': 'Education',
  'vehicles': 'Vehicles',
  'booking': 'Booking',
  'bookingHistory': 'Booking History',
  'pending': 'Pending',
  'accepted': 'Accepted',
  'reject': 'Reject',
  'historyDetail': 'History Detail',
  'informationFix': 'Information Fix',
  'carProblem': 'Car Problem',
  'technicaleRecommendation': 'Technicale Recommendation',
  'quote': 'Quote',
  'workOrder': 'Work Order',
  'invoice': 'Invoice',
  'book': 'Book',
  'balance': 'Balance',
  'branch': 'Branch',
  'branchLocator': 'Branch Locator',
  'garageLocator': 'Garage Locator',
  'district': 'District',
  'province': 'Province',
  'history': 'Payment History',
  'bookNow': ' BOOK NOW',
  'educationVideos': 'Education Videos',
  'popularVideos': 'Popular Videos',
  'allVideos': '  All Videos',
  'areYouSureToLogOut': 'Are you sure to log out?',
  'retry': 'Retry',
  'unauthorized': 'Your token expires. Please sign in again.',
  'success': 'Success',
  'sentSuccessfully': 'Sent Successfully!',
  'feedbackHasNotBeenSend': 'Feedback has not been send.',
  'invalidCodeNumber': 'Invalid Code Number.',
  'pleaseTryEnterYourCodeNumberAgain':
      'Please try enter your code number again.',
  'signout': 'Sign out',
  'nothingFound': 'Nothing found',
  'loginByFacebook': 'Log in by Faceboook',
  'somethingWhenWrong': 'Something when wrong',
  'done': 'Done',
  'myPage': 'My page',
  'changePhoto': 'Change photo',
  'settings': 'Settings',
  'reportForUpdate': 'Report for update',
  'faq': 'FAQ',
  'contact': 'Contact',
  'basic': 'Basic',
  'account': 'Account',
  'notification': 'Notification',
  'shareFriends': 'Share friends',
  'support': 'Support',
  'service': 'Service',
  'termOfService': 'Term of service',
  'privacyPolicy': 'Privacy policy',
  'version': 'Ver 1.0.1',
  'home': 'Home',
  'collection': 'Collection',
  'superPass': 'Super Pass',
  'yourVehicles': 'Your Vehicles',
  'days': 'days',
  'cars': 'Cars',
  'package': 'Package',
  'engineCoolantInspection': 'Engine Coolant Inspection',
  'total': 'Total',
  'used': 'Used',
  'remain': 'Remain',
  'voucher': 'Voucher',
  'feedBack': 'Feedback',
  'doYouWantToFeedback': 'Do you want to Feedback?',
  'contactUs': 'Contact Us',
  'about': 'About',
  'address': 'Address',
  'hotline': 'Hotline',
  'copyRight': 'Copyright© 2020',
  'membership': 'Membership',
  'membershipInfo': 'MEMBERSHIP INFO',
  'privacy': 'Privacy Policy ',
  'and': 'And ',
  'pleaseEnterCode': 'Please Enter Code',
  'voucherCode': 'Voucher Code',
  'addVoucher': 'Add Voucher',
  'enterYourCarProblem': 'Enter your car problem',
  'problem': 'Problem',
  'terms': 'Terms.',
  'bestDeal': 'BEST DEAL!',
  'news': 'News',
  'send': 'Send',
  'content': 'Content',
  'activities': 'Activities',
  'remove': 'Remove',
  'addComment': 'Add comment',
  'comments': 'Comments',
  'comment': 'Comment',
  'searchAnything': 'Search anything',
  'signingInIsCancelled': 'Signing in is cancelled.',
  'firstname': 'Firstname',
  'lastname': 'Lastname',
  'username': 'Username',
  'facebook': 'Facebook',
  'instagram': 'Instagram',
  'twitter': 'Twitter',
  'noResultFound': 'No result found',
  'noData': 'No data',
  'all': 'All',
  'mostView': 'Most view',
  'mostShare': 'Most share',
  'recommend': 'Recommend',
  'review': 'Review',
  'writeYourExperian': 'Write your Experian...',
  'normal': 'Normal',
  'poor': 'Poor',
  'good': 'Good',
  'veryGood': 'Very Good',
  'reply': 'Reply',
  'replies': 'Replies',
  'previousComments': 'Previous comments',
  'submit': 'Submit',
  'pleaseEnterYourSubject': 'Please enter your subject ',
  'enterYourMessageHere': 'Enter your message here ',
  'pleaseEnter': 'Please enter',
  'pleaseSelect': 'Please select',
  'replyComment': 'Reply comment',
  'logOut': 'Log out',
  'doYouWantToLogout': 'Do you want to Logout?',
  'defaultString': 'Default',
  'yourRequestUpdateHasBeenSent': 'Your request for update has been sent.',
  'yourContentCannotBeEmpty': 'Your content cannot be empty.',
  'tooManyRequestWereMade': 'Too many requests were made.',
  'latest': 'Latest',
  'sending': 'Sending',
  'information': 'Information',
  'articleDoesNotExist': 'Article deos not exist.',
  'selectImageSource': 'Select image source',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'filter': 'Filter',
  'doYouWantToLinkYourAccountWithFacebook':
      'Do you want to link your account with Facebook?',
  'doYouWantToLinkYourAccountWithInstagram':
      'Do you want to link your account with Instagram?',
  'doYouWantToLinkYourAccountWithTwitter':
      'Do you want to link your account with Twitter?',
  'enCounterErrorTryAgainLater': 'Encounter error. Please try again later.',
  'loginByApple': 'Log in by Apple',
  'update': 'Update',
  'userName': 'User name',
  'phoneNumber': 'Phone number',
  'gender': 'Gender',
  'female': 'Female',
  'male': 'Male',
  'other': 'Other',
  'email': 'Email',
  'create': 'Create',
  'add': 'Add',
  'addVehicle': 'Add Vehicle',
  'editVehicle': 'Edit Vehicle',
  'pleaseEnterUserName': 'Please enter user name',
  'edit': 'Edit',
  'delete': 'Delete',
  'action': 'Action',
  'areYouSureToDeleteThisComment': 'Are you sure to delete this comment?',
  'editComment': 'Edit comment',
  'yourCommentHasBeenUpdatedSuccessfully':
      'Your comment has been updated successfully.',
  'carYear': 'Car year ',
  'carBrand': 'Car brand ',
  'carModel': 'Car model ',
  'platNumber': 'Plat number',
  'vINNumber': 'VIN number',
  'color': 'Color',
  'fuelType': 'Fuel type',
  'remaining': 'Remaining',
  'serviceListsRemaid': 'Service lists Remaid',
  'vehiclePhoto': 'Vehicle photo',
  'titleVideo': 'Title Videos',
  'pleaseSelectCarYear': 'Please select car year ',
  'pleaseSelectCarBrand': 'Please select car brand ',
  'pleaseSelectCarModel': 'Please select car model ',
  'top': 'Top',
  'sorry': 'Sorry',
  'inquiry': 'Inquiry',
  'publicBeta': 'Public Beta',
  'signInWithApple': 'Sign in with Apple',
  'signInWithFacebook': 'Sign in with Facebook',
  'changeLanguage': 'Change Language',
  'goBack': 'Go back',
  'toDay': 'Today',
  'am': 'AM',
  'pm': 'PM',
  'payment': 'Payment History',
  'remainderServices': 'Remainder Services',
  'remainder': 'Remaind',
  'expire': 'Expire',
  'serviceDetail': 'Service Detail',
  'serviceListsRemainder': 'Service listsRemainder',
  'expireDate': 'Expire Date',
  'next': 'Next',
  'bookingServices': 'Booking-Services',
  'selectServices': 'Select Services',
  'selectMechanic': 'Select Mechanic',
  'free': 'Free',
  'busy': 'Busy',
  'time': 'Time',
  'hour': 'Hour',
  'description': 'Description',
  'thankForBookingOurTeamWill': 'Thank for Booking, our team will',
  'contactToYouSoon': 'contact to you soon !',
  'availableAt': 'Available at',
  'promotionDate': 'Promotion date',
  'comingSoon': 'Coming soon...'
};
