/*
| ---------------------------------------------------------------------- 
| Add More Action Button / Menu
| ----------------------------------------------------------------------     
|
|
|
|
*/

const kh = {
  'brandName': 'ឈ្មោះ',
  'noInternetConnection': 'គ្មានការភ្ជាប់អិនណឹនេតទេ',
  'lKhmer': 'ភាសាខ្មែរ',
  'lEnglish': 'ភាសាអង់គ្លេស់',
  'welcome': 'សូមស្វាគមន៍!',
  'enterYourMobileNumberToContinue': 'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នកដើម្បីបន្ត',
  'languages': 'ភាសា',
  'loadLanguage': 'ខ្មែរ',
  'selectLanguage': 'ជ្រើសរើស​ភាសា',
  'continue': 'បន្ត',
  'seconds': ' វិនាទី',
  'download': 'ទាញយក',
  'phoneNumberIncorrect': 'លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
  'pleaseEnterYourPhoneNumber': 'សូមបញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
  'confirmSMSCode': 'បញ្ជាក់លេខកូដសារ SMS',
  'weHaveSentYouAndSMSWithThe': 'យើងបានផ្ញើនិងផ្ញើសារទៅអ្នកតាមរយៈអ៊ីម៉ែល',
  'IDidNotGetTheCode': 'ខ្ញុំមិនបានទទួលលេខកូដទេ',
  'IHaveAgreeTo': 'ញុំយល់ព្រម',
  'the': '',
  'termsAndConditions': 'ល័ក្ខខ័ណ្ឌ',
  'codeTo': 'លេខកូដទៅ ',
  'loading': 'កំពុងផ្ទុក...',
  'error': 'កំហុស',
  'ok': 'យល់ព្រម',
  'yes': 'បាទ',
  'no': 'ទេ',
  'selectOption': 'ជ្រើសជម្រើស',
  'cancel': 'បោះបង់',
  'confirmation': 'ការបញ្ជាក់',
  'DoYouWantToRemove': 'តើអ្នកចង់យកចេញទេ?',
  'promotions': 'ការផ្សព្វផ្សាយ',
  'detail': 'ពត៌មានលំអិត',
  'seeAll': 'ឃើញ​ទាំងអស់',
  'menu': 'មឺនុយ (Menu)',
  'education': 'ការអប់រំ',
  'vehicles': 'យានយន្ត',
  'booking': 'ការកក់',
  'bookingHistory': 'ប្រវត្តិការកក់',
  'book': 'កក់',
  'pending': 'មិនទាន់សម្រេច',
  'accepted': 'ទទួលយក',
  'reject': 'បដិសេធ',
  'historyDetail': 'ប្រវត្តិលំអិត',
  'informationFix': 'ព័ត៌មានជួសជុល',
  'carProblem': 'បញ្ហារថយន្ត',
  'technicaleRecommendation': 'អនុសាសន៍បច្ចេកទេស',
  'selectPackages': 'ជ្រើសរើសកញ្ចប់',
  'quote': 'សម្រង់',
  'workOrder': 'លំដាប់ការងារ',
  'invoice': 'វិក័យប័ត្រ',
  'balance': 'សាច់ប្រាក់',
  'review': 'ពិនិត្យឡើងវិញ',
  'normal': 'ធម្មតា',
  'poor': 'មិនសូវល្អ',
  'good': 'ល្អ​',
  'veryGood': 'ល្អ​ណាស់',
  'writeYourExperian': 'សរសេរអ្នកជំនាញរបស់អ្នក...',
  'branch': 'ទីតាំងសាខា',
  'branchLocator': 'ទីតាំងសាខា',
  'garageLocator': ' យានដ្ឋានបណ្តាញប្រតិបត្តិការ',
  'district': 'ស្រុក',
  'province': 'ខេត្ត',
  'history': 'ប្រវត្តិទូទាត់',
  'bookNow': 'កក់​ឥឡូវនេះ',
  'educationVideos': 'វីដេអូអប់រំ',
  'popularVideos': 'វីដេអូពេញនិយម',
  'allVideos': 'វីដេអូទាំងអស់',
  'areYouSureToLogOut': 'តើអ្នកប្រាកដជាចេញហើយឬ?',
  'retry': 'ព្យាយាមម្តងទៀត',
  'unauthorized': 'ថូខឹនរបស់អ្នកផុតកំណត់សូមចូលម្តងទៀត។',
  'success': 'ជោគជ័យ',
  'sentSuccessfully': 'បានផ្ញើដោយជោគជ័យ!',
  'feedbackHasNotBeenSend': 'មតិប្រតិកម្មមិនត្រូវបានផ្ញើទេ។',
  'voucher': 'ប័ណ្ណទូទាត់',
  'feedBack': 'ផ្តល់យោបល់',
  'invalidCodeNumber': 'លេខកូដមិនត្រឹមត្រូវ។',
  'pleaseTryEnterYourCodeNumberAgain': 'សូមព្យាយាមបញ្ចូលលេខកូដរបស់អ្នកម្តងទៀត។',
  'doYouWantToFeedback': 'តើអ្នកចង់ផ្តល់យោបល់?',
  'contactUs': 'ទាក់ទង​មក​ពួក​យើង',
  'about': 'អំពី',
  'address': 'អាសយដ្ឋាន',
  'hotline': 'ទូរសព្ទ័បន្ទាន់',
  'signOut': 'ចេញ',
  'nothingFound': 'គ្មានអ្វីរកឃើញទេ',
  'loginByFacebook': 'ចូលតាម Faceboook',
  'done': 'រួចរាល់',
  'myPage': 'ទំព័ររបស់ខ្ញុំ',
  'changePhoto': 'ប្តូររូបថត',
  'settings': 'ការកំណត់',
  'reportForUpdate': 'របាយការណ៍សម្រាប់ការធ្វើបច្ចុប្បន្នភាព',
  'faq': 'សំណួរគេសួរញឹកញាប់',
  'contact': 'ទំនាក់ទំនង',
  'basic': 'មូលដ្ឋាន',
  'account': 'គណនី',
  'notification': 'ការជូនដំណឹង',
  'shareFriends': 'ចែករំលែកមិត្តភក្តិ',
  'support': 'ការគាំទ្រ',
  'service': 'សេវាកម្ម',
  'termOfService': 'រយៈពេលនៃសេវាកម្ម',
  'privacyPolicy': 'គោលការណ៍ឯកជនភាព',
  'version': 'ជំនាន់ 1.0.1',
  'home': 'ទំព័រដើម',
  'collection': 'ការប្រមូល',
  'superPass': 'Super Pass',
  'yourVehicles': 'យានយន្តរបស់អ្នក',
  'days': 'ថ្ងៃ',
  'cars': 'ឡាន',
  'package': 'កញ្ចប់',
  'engineCoolantInspection': 'អធិការកិច្ចម៉ាស៊ីនត្រជាក់',
  'total': '  សរុប',
  'used': ' បានប្រើ',
  'remain': '  នៅសល់',
  'copyRight': 'រក្សាសិទ្ធិ© ២០២០',
  'membership': 'សមាជិកភាព',
  'membershipInfo': 'ព័ត៌មានសមាជិកភាព',
  'privacy': 'គោលការណ៍ភាពឯកជន ',
  'and': 'និង ',
  'pleaseEnterCode': 'សូមបញ្ចូលលេខកូដ',
  'voucherCode': 'កូដប័ណ្ណ',
  'addVoucher': 'បន្ថែមប័ណ្ណ',
  'enterYourCarProblem': 'បញ្ចូលបញ្ហាឡានរបស់អ្នក',
  'problem': 'បញ្ហា',
  'terms': 'ល័ក្ខខ័ណ្ឌ។',
  'bestDeal': 'ល្អបំផុត!',
  'news': 'ព័ត៌មាន',
  'send': 'ផ្ញើ',
  'content': 'មាតិកា',
  'activities': 'សកម្មភាព',
  'remove': 'លុបចេញ',
  'addComment': 'បន្ថែមមតិយោបល់',
  'comments': 'យោបល់',
  'comment': 'យោបល់',
  'searchAnything': 'ស្វែងរកអ្វីទាំងអស់',
  'signingInIsCancelled': 'ត្រូវបានលុបចោលការចូល',
  'firstname': 'ឈ្មោះដំបូង',
  'lastname': 'នាមត្រកូល',
  'username': 'ឈ្មោះអ្នកប្រើ',
  'facebook': 'ហ្វេសប៊ុក',
  'instagram': 'Instagram',
  'twitter': 'Twitter',
  'noResultFound': 'រកមិនឃើញលទ្ធផល',
  'noData': 'គ្មានទិន្នន័យ',
  'all': 'ទាំងអស់',
  'mostView': 'មើលច្រើនបំផុត',
  'mostShare': 'ចែករំលែកច្រើនបំផុត',
  'recommend': 'ផ្តល់អនុសាសន៍',
  'reply': 'ឆ្លើយតប',
  'replies': 'ឆ្លើយតប',
  'previousComments': 'យោបល់មុន',
  'submit': 'ការដាក់ស្នើ',
  'pleaseEnterYourSubject': 'សូមបញ្ចូលប្រធានបទរបស់អ្នក ',
  'enterYourMessageHere': 'បញ្ចូលសាររបស់អ្នកនៅទីនេះ ',
  'pleaseEnter': 'សូមបញ្ចូល',
  'pleaseSelect': 'សូមជ្រើសរើស',
  'replyComment': 'ឆ្លើយតបមតិយោបល់',
  'logOut': 'ចេញ',
  'doYouWantToLogout': 'តើអ្នកចង់ចាកចេញទេ?',
  'defaultString': 'លំនាំដើម',
  'yourRequestUpdateHasBeenSent':
      'សំណើរបស់អ្នកសម្រាប់ការធ្វើបច្ចុប្បន្នភាពត្រូវបានផ្ញើ',
  'yourContentCannotBeEmpty': 'មាតិការបស់អ្នកមិនអាចទទេបានទេ',
  'tooManyRequestWereMade': 'មានសំណើច្រើនណាស់',
  'latest': 'ចុងក្រោយ',
  'sending': 'ការផ្ញើ',
  'information': 'ព័ត៌មាន',
  'articleDoesNotExist': 'មិនមានអត្ថបទទេ',
  'selectImageSource': 'ជ្រើសរើសប្រភពរូបភាព',
  'camera': 'ម៉ាស៊ីនថត',
  'gallery': 'រូបភាព',
  'filter': 'ច្រោះយក',
  'somethingWhenWrong': 'អ្វីមួយនៅពេលដែលខុស',
  'doYouWantToLinkYourAccountWithFacebook':
      'តើអ្នកចង់ភ្ជាប់គណនីរបស់អ្នកជាមួយហ្វេសប៊ុកទេ?',
  'doYouWantToLinkYourAccountWithInstagram':
      'តើអ្នកចង់ភ្ជាប់គណនីរបស់អ្នកជាមួយ Instagram ទេ?',
  'doYouWantToLinkYourAccountWithTwitter':
      'តើអ្នកចង់ភ្ជាប់គណនីរបស់អ្នកជាមួយ Twitter ទេ?',
  'incounterErrorTryAgainLater': 'ជួបប្រទះកំហុសសូមព្យាយាមម្តងទៀតពេលក្រោយ។',
  'userName': 'ឈ្មោះ​អ្នកប្រើប្រាស់ ',
  'phoneNumber': 'លេខទូរសព្ទ ',
  'gender': 'ភេទ ',
  'female': 'ស្រី',
  'male': 'ប្រុស',
  'other': 'ផ្សេងទៀត',
  'email': 'អ៊ីមែល',
  'create': 'បង្កើត',
  'pleaseEnterUserName': 'សូមបញ្ចូលឈ្មោះរបស់អ្នក',
  'loginByApple': 'ចូលដោយ Apple',
  'edit': 'កែសម្រួល',
  'add': 'បញ្ចូល',
  'addVehicle': 'បញ្ចូល យានយន្ត',
  'editVehicle': 'កែប្រែ យានយន្ត',
  'update': 'កែសម្រួល',
  'delete': 'លុប',
  'action': 'សកម្មភាព',
  'areYouSureToDeleteThisComment': 'តើអ្នកប្រាកដជាលុបមតិនេះឬ?',
  'editComment': 'កែសម្រួលមតិយោបល់',
  'yourCommentHasBeenUpdatedSuccessfully':
      'យោបល់របស់អ្នកត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ',
  'carYear': 'ឆ្នាំរថយន្ត ',
  'carBrand': 'ម៉ាករថយន្ត ',
  'carModel': 'គំរូរថយន្ត ',
  'platNumber': 'ផ្លាក់លេខ',
  'vINNumber': 'លេខ​ តួម៉ាស៊ីន',
  'color': 'ពណ៌',
  'fuelType': 'ប្រភេទឥន្ធនៈ',
  'vehiclePhoto': 'រូបថតរថយន្ត',
  'titleVideo': 'ចំណងជើងវីដេអូ',
  'pleaseSelectCarYear': 'សូមជ្រើសរើសឆ្នាំរថយន្ត ',
  'pleaseSelectCarBrand': 'សូមជ្រើសរើសឆ៉ាករថយន្ត ',
  'pleaseSelectCarModel': 'សូមជ្រើសរើសគំរូរថយន្ត ',
  'top': 'ខាងលើ',
  'sorry': 'សុំទោស',
  'inquiry': 'សាកសួរ',
  'publicBeta': 'សាធារណៈបេតា',
  'signInWithApple': 'ចូលជាមួយ Apple',
  'signInWithFacebook': 'ចូលជាមួយហ្វេសប៊ុក',
  'changeLanguage': 'ផ្លាស់ប្តូរភាសា',
  'goBack': 'ត្រលប់ក្រោយ',
  'toDay': 'ថ្ងៃនេះ',
  'am': 'ព្រឹក',
  'pm': 'ល្ងាច',
  'remaining': 'នៅសល់',
  'serviceListsRemaid': 'បញ្ជីសេវាកម្មនៅសល់',
  'payment': 'ប្រវត្តិទូទាត់',
  'remainderServices': 'សេវាកម្មនៅសល់',
  'remainder': 'នៅសល់',
  'expire': 'ផុតកំណត់',
  'serviceDetail': 'ពត៌មានលំអិតសេវាកម្ម',
  'serviceListsRemainder': 'បញ្ជីសេវាកម្មនៅសល់',
  'expireDate': 'ផុតកំណត់កាលបរិច្ឆេទ',
  'next': 'បន្ទាប់',
  'bookingServices': 'សេវាកម្មកក់',
  'selectServices': 'ជ្រើសរើសសេវាកម្ម',
  'selectMechanic': 'ជ្រើសរើសមេកានិក',
  'free': 'ឥតគិតថ្លៃ',
  'busy': 'រវល់',
  'time': 'ពេលវេលា',
  'hour': 'ម៉ោង',
  'description': 'ការពិពណ៌នា',
  'thankForBookingOurTeamWill': 'សូមអរគុណសម្រាប់ការកក់ក្រុមរបស់យើងនឹង',
  'contactToYouSoon': 'ទាក់ទងមកអ្នកឆាប់ៗ !',
  'availableAt': 'មាននៅទីតាំង',
  'promotionDate': 'កាលបរិច្ឆេទផ្សព្វផ្សាយ',
  'comingSoon': 'នឹងមកដល់ឆាប់ៗនេះ...'
};
